######################################################################
# Automatically generated by qmake (3.0) ?? 5? 4 08:47:28 2017
######################################################################

TEMPLATE = app
TARGET = YUVOverlay_V4L2_Test
INCLUDEPATH += .

# Input
HEADERS += alsa.h gather_picture.h
SOURCES += alsa.cpp gather_picture.c main.cpp


INCLUDEPATH += -I/opt/yogurt/i.MX6-PD15.3.0/sysroots/cortexa9hf-vfp-neon-phytec-linux-gnueabi/usr/include


LIBS += -L/opt/yogurt/i.MX6-PD15.3.0/sysroots/cortexa9hf-vfp-neon-phytec-linux-gnueabi/usr/lib  -lasound
